jobs:
  - name: ztimer-image
    type: runCLI
    steps:
      - IN: ztimer-docker-cli-config
      - TASK:
        - script: npm install ztimer.ui@rc
        - script: docker build node_modules/ztimer.ui -t zthun/ztimer:rc
        - script: docker push zthun/ztimer:rc
      - OUT: ztimer-rc-image

  - name: ztimer-manifest
    type: manifest
    steps:
      - IN: ztimer-image
      - IN: ztimer-rc-image
      - IN: core-docker-options
      - TASK: managed

  - name: ztimer-deploy-stage
    type: deploy
    steps:
      - IN: ztimer-manifest
      - IN: zthunworks-aws-stage-cluster
      - TASK: managed

  - name: ztimer-deploy-prod
    type: deploy
    steps:
      - IN: ztimer-deploy-stage
        switch: off
      - IN: zthunworks-aws-prod-cluster
      - TASK: managed

  - name: ztimer-update-docker-image
    type: runCLI
    steps:
      - IN: ztimer-docker-cli-config
      # - IN: ztimer-deploy-prod
      - TASK:
        - script: SOURCE_IMAGE=zthun/ztimer
        - script: SOURCE_TAG=rc
        - script: NPMVERSION=$(npm dist-tag ls ztimer.ui | grep rc)
        - script: docker pull zthun/ztimer:rc
        - script: SEMVAR=${NPMVERSION//rc:/}
        - script: echo Tagging rc version as $SEMVAR.
        - script: docker tag $SOURCE_IMAGE:$SOURCE_TAG $SOURCE_IMAGE:$SEMVAR
        - script: echo Tagging rc version as latest.
        - script: docker tag $SOURCE_IMAGE:$SOURCE_TAG $SOURCE_IMAGE:latest
        # - script: docker push zthun:ztimer:$SEMVAR
        # - script: docker push zthun:ztimer:latest
